import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import { ThemeProvider } from "next-themes";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider attribute="class" defaultTheme="light">
        <Header />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
